import type { Category, CategoryPageMeta, CategorySlug, NavItem, Product, Testimonial } from './types'

const U = {
  obsidian: 'photo-1764698072732-ea0230fc5d8e',
  jacket: 'photo-1783430455894-9858f0efcb06',
  havana: 'photo-1741709847811-e02d0502e46f',
  noir: 'photo-1742319692068-f63de5b5d4b0',
  polo: 'photo-1783097906573-9bdb0225c39a',
  suitStreet: 'photo-1741709847860-85286566b5c9',
  casual: 'photo-1763750581767-b367bcd6c117',
  hero: 'photo-1761727074976-ea99983f8e0d',
  blazer: 'photo-1627379114594-7aff6664cd94',
}

const img = (id: string, w = 600, h = 800) =>
  `https://images.unsplash.com/${id}?w=${w}&h=${h}&fit=crop&auto=format`

const SIZES = ['P', 'M', 'G', 'GG', 'XGG']

export const PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Camisa Obsidian',
    category: 'Camisas',
    categorySlug: 'camisas',
    price: 349,
    oldPrice: 420,
    tag: 'Novo',
    tagColor: '#1a5c3a',
    images: [img(U.obsidian), img(U.polo), img(U.hero)],
    colors: [
      { name: 'Preto', hex: '#151413', img: img(U.obsidian) },
      { name: 'Grafite', hex: '#4a4a47', img: img(U.polo) },
      { name: 'Azul-noite', hex: '#1c2b3a', img: img(U.hero) },
    ],
    sizes: SIZES,
    alt: 'Homem de camisa preta desbotada apoiado na parede',
    description:
      'Camisa em sarja premium com caimento slim e acabamento reforçado. Ideal para o dia a dia e para o escritório.',
    benefits: ['Tecido 100% algodão', 'Caimento slim', 'Lavagem premium'],
    featured: true,
  },
  {
    id: 2,
    name: 'Jaqueta Carbone',
    category: 'Jaquetas',
    categorySlug: 'casual',
    price: 689,
    oldPrice: null,
    tag: 'Exclusivo',
    tagColor: '#3a2a0a',
    images: [img(U.jacket), img(U.blazer), img(U.noir)],
    colors: [
      { name: 'Carbono', hex: '#2b2b2b', img: img(U.jacket) },
      { name: 'Preto', hex: '#111111', img: img(U.blazer) },
      { name: 'Grafite', hex: '#3a3a38', img: img(U.noir) },
    ],
    sizes: SIZES,
    alt: 'Homem com jaqueta escura olhando por cima do ombro',
    description:
      'Jaqueta bomber em tecido técnico com toque suave, forro térmico e zíperes metálicos de alta durabilidade.',
    benefits: ['Forro térmico', 'Tecido técnico', 'Resistente à água'],
    featured: true,
  },
  {
    id: 3,
    name: 'Terno Havana',
    category: 'Ternos',
    categorySlug: 'ternos',
    price: 1290,
    oldPrice: 1580,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.havana), img(U.suitStreet), img(U.casual)],
    colors: [
      { name: 'Caramelo', hex: '#6b4a2f', img: img(U.havana) },
      { name: 'Cinza', hex: '#3a3a38', img: img(U.suitStreet) },
      { name: 'Marinho', hex: '#1e3352', img: img(U.casual) },
    ],
    sizes: SIZES,
    alt: 'Homem de terno marrom em pose elegante',
    description:
      'Terno de corte italiano em lã fria, com paletó estruturado e calça de alfaiataria para ocasiões especiais.',
    benefits: ['Lã fria premium', 'Corte italiano', 'Paletó estruturado'],
    featured: true,
  },
  {
    id: 4,
    name: 'Conjunto Noir',
    category: 'Conjuntos',
    categorySlug: 'ternos',
    price: 890,
    oldPrice: null,
    tag: 'Bestseller',
    tagColor: '#1a3a5c',
    images: [img(U.noir), img(U.jacket), img(U.hero)],
    colors: [
      { name: 'Preto', hex: '#111111', img: img(U.noir) },
      { name: 'Carbono', hex: '#2a2a28', img: img(U.jacket) },
      { name: 'Cinza', hex: '#3a3a38', img: img(U.hero) },
    ],
    sizes: SIZES,
    alt: 'Homem em terno preto com óculos de sol',
    description:
      'Conjunto com camisa e calça em tecido premium que não amassa, perfeito para eventos e ocasiões formais.',
    benefits: ['Não amassa', 'Alfaiataria premium', 'Look completo'],
    featured: true,
  },
  {
    id: 5,
    name: 'Camisa Oxford',
    category: 'Camisas',
    categorySlug: 'camisas',
    price: 299,
    oldPrice: null,
    tag: 'Essencial',
    tagColor: '#2a3a5c',
    images: [img(U.polo), img(U.obsidian), img(U.hero)],
    colors: [
      { name: 'Branco', hex: '#e8e6df', img: img(U.polo) },
      { name: 'Azul-claro', hex: '#9db0c0', img: img(U.obsidian) },
      { name: 'Preto', hex: '#111111', img: img(U.hero) },
    ],
    sizes: SIZES,
    alt: 'Homem de gola-preta clássica',
    description:
      'A camisa oxford que nunca sai de moda: tecido estruturado, colarinho firme e botões de madrepérola.',
    benefits: ['Tecido oxford premium', 'Colarinho estruturado', 'Botões de madrepérola'],
  },
  {
    id: 6,
    name: 'Camisa Lino',
    category: 'Camisas',
    categorySlug: 'camisas',
    price: 329,
    oldPrice: null,
    tag: 'Novo',
    tagColor: '#1a5c3a',
    images: [img(U.hero), img(U.casual), img(U.polo)],
    colors: [
      { name: 'Bege', hex: '#c9b28a', img: img(U.hero) },
      { name: 'Natural', hex: '#d8cbb0', img: img(U.casual) },
      { name: 'Preto', hex: '#111111', img: img(U.polo) },
    ],
    sizes: SIZES,
    alt: 'Homem em corredor editorial com camisa leve',
    description:
      'Camisa de linho puro com caimento solto e frescor incomparável para os dias quentes.',
    benefits: ['100% linho', 'Caimento solto', 'Respirabilidade máxima'],
  },
  {
    id: 7,
    name: 'Camisa Flanela',
    category: 'Camisas',
    categorySlug: 'camisas',
    price: 199,
    oldPrice: 279,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.casual), img(U.blazer), img(U.jacket)],
    colors: [
      { name: 'Xadrez-cinza', hex: '#4a4a47', img: img(U.casual) },
      { name: 'Carvão', hex: '#2b2b2b', img: img(U.blazer) },
      { name: 'Vinho', hex: '#5c1a1a', img: img(U.jacket) },
    ],
    sizes: SIZES,
    alt: 'Homem casual com camisa de flanela',
    description:
      'Flanela escovada com toque macio e quente — o essencial do inverno para looks despojados.',
    benefits: ['Flanela escovada', 'Toque macio', 'Aquecimento extra'],
  },
  {
    id: 8,
    name: 'Terno London',
    category: 'Ternos',
    categorySlug: 'ternos',
    price: 1190,
    oldPrice: 1490,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.suitStreet), img(U.havana), img(U.noir)],
    colors: [
      { name: 'Cinza-chumbo', hex: '#3a3a38', img: img(U.suitStreet) },
      { name: 'Caramelo', hex: '#6b4a2f', img: img(U.havana) },
      { name: 'Preto', hex: '#111111', img: img(U.noir) },
    ],
    sizes: SIZES,
    alt: 'Homem de terno cinza andando pela rua',
    description:
      'Terno clássico inglês em lã fria, com paletó de ombro marcado e calça reta de alfaiataria.',
    benefits: ['Ombro marcado', 'Lã fria premium', 'Calça reta'],
  },
  {
    id: 9,
    name: 'Blazer Moleskin',
    category: 'Ternos',
    categorySlug: 'ternos',
    price: 999,
    oldPrice: null,
    tag: 'Exclusivo',
    tagColor: '#3a2a0a',
    images: [img(U.blazer), img(U.suitStreet), img(U.jacket)],
    colors: [
      { name: 'Preto', hex: '#111111', img: img(U.blazer) },
      { name: 'Cinza', hex: '#3a3a38', img: img(U.suitStreet) },
      { name: 'Moleskin', hex: '#6b5540', img: img(U.jacket) },
    ],
    sizes: SIZES,
    alt: 'Homem em blazer preto apoiado no corrimão',
    description:
      'Blazer em moleskin aveludado que eleva qualquer produção — do smart casual ao formal.',
    benefits: ['Moleskin aveludado', 'Versátil', 'Alfaiataria premium'],
  },
  {
    id: 10,
    name: 'Calça Chino Sand',
    category: 'Calças',
    categorySlug: 'calcas',
    price: 249,
    oldPrice: 299,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.casual), img(U.jacket), img(U.hero)],
    colors: [
      { name: 'Sand', hex: '#c2a878', img: img(U.casual) },
      { name: 'Cáqui', hex: '#8a7a5a', img: img(U.jacket) },
      { name: 'Marinho', hex: '#1e3352', img: img(U.hero) },
    ],
    sizes: SIZES,
    alt: 'Homem casual de óculos com calça chino',
    description:
      'Chino em algodão premium com caimento slim e cintura ajustada — a peça curinga do guarda-roupa.',
    benefits: ['Algodão premium', 'Caimento slim', 'Cintura ajustada'],
  },
  {
    id: 11,
    name: 'Calça Sarja Premium',
    category: 'Calças',
    categorySlug: 'calcas',
    price: 329,
    oldPrice: null,
    tag: 'Novo',
    tagColor: '#1a5c3a',
    images: [img(U.jacket), img(U.noir), img(U.polo)],
    colors: [
      { name: 'Carbono', hex: '#2b2b2b', img: img(U.jacket) },
      { name: 'Preto', hex: '#111111', img: img(U.noir) },
      { name: 'Azul-noite', hex: '#1c2b3a', img: img(U.polo) },
    ],
    sizes: SIZES,
    alt: 'Homem com jaqueta e calça de sarja',
    description:
      'Calça de sarja pesada com barra à máquina, ideal para o trabalho e para encontros urbanos.',
    benefits: ['Sarja pesada', 'Barra à máquina', 'Costuras reforçadas'],
  },
  {
    id: 12,
    name: 'Calça Alfaiataria Navy',
    category: 'Calças',
    categorySlug: 'calcas',
    price: 459,
    oldPrice: null,
    tag: 'Essencial',
    tagColor: '#2a3a5c',
    images: [img(U.havana), img(U.suitStreet), img(U.blazer)],
    colors: [
      { name: 'Marinho', hex: '#1e3352', img: img(U.havana) },
      { name: 'Cinza', hex: '#3a3a38', img: img(U.suitStreet) },
      { name: 'Preto', hex: '#111111', img: img(U.blazer) },
    ],
    sizes: SIZES,
    alt: 'Homem de terno marrom com calça de alfaiataria',
    description:
      'Calça de alfaiataria com vinco perfeito e tecido que não amassa, pronta para compor looks formais.',
    benefits: ['Vinco perfeito', 'Não amassa', 'Tecido premium'],
  },
  {
    id: 13,
    name: 'Calça Jogger Tech',
    category: 'Calças',
    categorySlug: 'calcas',
    price: 259,
    oldPrice: null,
    tag: 'Novo',
    tagColor: '#1a5c3a',
    images: [img(U.polo), img(U.hero), img(U.casual)],
    colors: [
      { name: 'Preto', hex: '#111111', img: img(U.polo) },
      { name: 'Grafite', hex: '#3a3a38', img: img(U.hero) },
      { name: 'Areia', hex: '#c2b29a', img: img(U.casual) },
    ],
    sizes: SIZES,
    alt: 'Homem de gola-preta com calça jogger',
    description:
      'Jogger em tecido técnico com elástico regulável e bolsos discretos — conforto para todos os momentos.',
    benefits: ['Tecido técnico', 'Elástico regulável', 'Bolsos discretos'],
  },
  {
    id: 14,
    name: 'Moletom Oversize',
    category: 'Casual',
    categorySlug: 'casual',
    price: 219,
    oldPrice: 279,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.casual), img(U.jacket), img(U.blazer)],
    colors: [
      { name: 'Cinza-escuro', hex: '#3a3a38', img: img(U.casual) },
      { name: 'Preto', hex: '#111111', img: img(U.jacket) },
      { name: 'Off-white', hex: '#d8d3c9', img: img(U.blazer) },
    ],
    sizes: SIZES,
    alt: 'Homem casual com óculos de sol',
    description:
      'Moletom oversized em algodão penteado com forro felpudo — a definição de conforto com atitude.',
    benefits: ['Algodão penteado', 'Forro felpudo', 'Modelagem oversized'],
  },
  {
    id: 15,
    name: 'Blusão Bomber',
    category: 'Casual',
    categorySlug: 'casual',
    price: 549,
    oldPrice: 659,
    tag: 'Promoção',
    tagColor: '#5c1a1a',
    images: [img(U.jacket), img(U.casual), img(U.noir)],
    colors: [
      { name: 'Carbono', hex: '#2b2b2b', img: img(U.jacket) },
      { name: 'Verde-escuro', hex: '#2c3a2c', img: img(U.casual) },
      { name: 'Preto', hex: '#111111', img: img(U.noir) },
    ],
    sizes: SIZES,
    alt: 'Homem com jaqueta escura olhando por cima do ombro',
    description:
      'Blusão bomber estruturado com gola alta e zíper metálico — acabamento técnico para o inverno.',
    benefits: ['Gola alta', 'Zíper metálico', 'Estruturado'],
  },
  {
    id: 16,
    name: 'Polo Piqué',
    category: 'Casual',
    categorySlug: 'casual',
    price: 189,
    oldPrice: null,
    tag: 'Essencial',
    tagColor: '#2a3a5c',
    images: [img(U.polo), img(U.obsidian), img(U.hero)],
    colors: [
      { name: 'Preto', hex: '#111111', img: img(U.polo) },
      { name: 'Grafite', hex: '#4a4a47', img: img(U.obsidian) },
      { name: 'Azul-noite', hex: '#1c2b3a', img: img(U.hero) },
    ],
    sizes: SIZES,
    alt: 'Homem de gola-preta preta',
    description:
      'Polo em piqué de algodão com gola canelada que mantém o caimento — elegância sem esforço.',
    benefits: ['Piqué de algodão', 'Gola canelada', 'Caimento firme'],
  },
]

export const FEATURED_PRODUCTS = PRODUCTS.filter(p => p.featured)

export const TESTIMONIALS: Testimonial[] = [
  {
    name: 'Lucas Ferreira',
    city: 'São Paulo, SP',
    text: 'A qualidade das peças superou minhas expectativas. O Terno Havana chegou impecável, com acabamento de altíssimo nível. Voltarei com certeza.',
    rating: 5,
  },
  {
    name: 'Matheus Andrade',
    city: 'Rio de Janeiro, RJ',
    text: 'A Foka tem o melhor equilíbrio entre estilo urbano e sofisticação. Uso as camisas no trabalho e nas saídas — sempre recebo elogios.',
    rating: 5,
  },
  {
    name: 'Rafael Oliveira',
    city: 'Curitiba, PR',
    text: 'Entrega rápida, embalagem cuidadosa e as peças são exatamente como no site. Finalmente uma marca que entende o que o homem moderno quer.',
    rating: 5,
  },
]

export const CATEGORIES: Category[] = [
  { name: 'Camisas', count: '48 peças', img: img(U.polo, 500, 640), alt: 'Homem de gola-preta preta', slug: 'camisas' },
  { name: 'Ternos', count: '24 peças', img: img(U.suitStreet, 500, 640), alt: 'Homem de terno na rua', slug: 'ternos' },
  { name: 'Calças', count: '36 peças', img: img(U.jacket, 500, 640), alt: 'Homem com jaqueta escura', slug: 'calcas' },
  { name: 'Casual', count: '62 peças', img: img(U.casual, 500, 640), alt: 'Homem casual com óculos de sol', slug: 'casual' },
]

export const NAV_ITEMS: NavItem[] = [
  { label: 'Coleções', to: '/colecoes' },
  { label: 'Camisas', to: '/camisas' },
  { label: 'Ternos', to: '/ternos' },
  { label: 'Calças', to: '/calcas' },
  { label: 'Casual', to: '/casual' },
  { label: 'Promoções', to: '/promocoes' },
]

export const CATEGORY_PAGES: Record<CategorySlug, CategoryPageMeta> = {
  camisas: {
    title: 'Camisas',
    kicker: 'PEÇAS-CHAVE DO GUARDA-ROUPA',
    description: 'Camisas de sarja, linho e flanela com caimento impecável — do escritório ao fim de semana.',
    banner: img(U.obsidian, 1600, 900),
  },
  ternos: {
    title: 'Ternos',
    kicker: 'SOFISTICAÇÃO DE ALFAIATARIA',
    description: 'Corte italiano, lã fria premium e modelagem que veste como uma luva.',
    banner: img(U.havana, 1600, 900),
  },
  calcas: {
    title: 'Calças',
    kicker: 'CAIMENTO PERFEITO',
    description: 'Chino, sarja, alfaiataria e jogger — a base de qualquer look masculino.',
    banner: img(U.suitStreet, 1600, 900),
  },
  casual: {
    title: 'Casual',
    kicker: 'ESTILO SEM ESFORÇO',
    description: 'Jaquetas, moletons e blusões para o homem moderno no dia a dia.',
    banner: img(U.casual, 1600, 900),
  },
}

export const MARQUEE_ITEMS = [
  'FEITO PARA DURAR',
  'ESTILO SEM ESFORÇO',
  'INVERNO 2026',
  'CORTE PRECISO',
  'TECIDOS PREMIUM',
  'ENVIO EM 48H',
]
